"""Lexers and language detection for the eSim code editor.

SPICE gets a purpose-built :class:`SpiceLexer` (the stock Scintilla
SPICE lexer cannot distinguish a component instance from a node and
miscolours stray single letters).  Verilog and VHDL use Scintilla's
mature built-in lexers.
"""

import os
import re

try:
    from PyQt6.Qsci import (
        QsciLexerCustom,
        QsciLexerVerilog,
        QsciLexerVHDL,
        QsciScintilla,
    )
    HAS_QSCI = True
except ImportError:               # QScintilla not installed / failed to load
    # QScintilla is an *optional* dependency, but the pure-Python half of this
    # module (language_for / is_generated / comment_token) is imported by
    # PlainEditor -- the Qsci-free fallback editor -- which the project
    # explorer, and therefore the whole app, pulls in at startup. An
    # unguarded import here meant a missing Qsci.pyd never showed a window at
    # all. Stand in placeholder bases so the class statements below still
    # execute; they are never instantiated because make_lexer() bails out.
    QsciLexerCustom = QsciLexerVerilog = QsciLexerVHDL = object
    QsciScintilla = None
    HAS_QSCI = False


# Scintilla fold-level flags (stable ABI constants).
_SC_FOLDLEVELBASE = 0x400
_SC_FOLDLEVELHEADERFLAG = 0x2000
_SCI_SETFOLDLEVEL = getattr(QsciScintilla, "SCI_SETFOLDLEVEL", 2222)
_SCI_LINEFROMPOSITION = getattr(QsciScintilla, "SCI_LINEFROMPOSITION", 2166)
_SCI_POSITIONFROMLINE = getattr(QsciScintilla, "SCI_POSITIONFROMLINE", 2167)

# Above this many lines we skip the (full-document) fold recompute to
# keep very large netlists responsive.
_FOLD_LINE_LIMIT = 20000

# Directives that open / close a foldable region.
_FOLD_OPEN = {".subckt", ".control", ".if", ".macro"}
_FOLD_CLOSE = {".ends", ".endc", ".endif", ".eom"}


def _blen(chunk):
    """Byte length of *chunk* (Scintilla styles in bytes)."""
    return len(chunk) if chunk.isascii() else len(chunk.encode("utf-8"))


# Extensions grouped by language (lower-case, with leading dot).
_SPICE_EXT = {
    ".cir", ".cirout", ".sub", ".lib", ".mod", ".net", ".ckt",
    ".sp", ".spice", ".cki", ".inc",
}
_VERILOG_EXT = {".v", ".va", ".vams", ".sv", ".vh"}
_VHDL_EXT = {".vhd", ".vhdl"}

# Files generated by eSim / ngspice and overwritten on the next run.
GENERATED_EXT = {".cirout", ".out", ".log"}

# Top-level decks whose very first line is the SPICE title line: the
# simulator ignores it as a comment no matter what it contains, so a
# title that happens to start with a device letter must not be coloured
# as an instance.  Library/include fragments have no title line.
_TITLE_DECK_EXT = {
    ".cir", ".cirout", ".net", ".ckt", ".sp", ".spice", ".cki",
}

# SPICE element letters: first char of an instance line.
_DEVICE_LETTERS = set("RCLVIDQMXBEFGHJKSTWOUZPA")

# Source / analysis keywords that may appear bare on an element line
# (e.g. ``V1 n+ n- DC 5 AC 1 SIN(0 1 1k)``); coloured like functions so
# they don't read as nodes.
_SOURCE_KEYWORDS = {
    "dc", "ac", "sin", "sine", "pulse", "pwl", "exp", "sffm", "am",
    "trnoise", "trrandom", "pat", "port", "noise",
}


class SpiceLexer(QsciLexerCustom):
    """Grammar-aware SPICE / ngspice netlist lexer."""

    DEFAULT = 0
    COMMENT = 1
    DIRECTIVE = 2
    INSTANCE = 3
    NUMBER = 4
    PARAMETER = 5
    STRING = 6
    OPERATOR = 7
    EXPRESSION = 8
    COMMAND = 9
    FUNCTION = 10
    NODE = 11

    _NAMES = {
        0: "Default", 1: "Comment", 2: "Directive",
        3: "Instance device", 4: "Number", 5: "Parameter",
        6: "String", 7: "Operator", 8: "Expression",
        9: "Command", 10: "Function", 11: "Node net",
    }

    # in-line token scanner (applied after the positional first token)
    _TOKEN_RE = re.compile(
        r"""
          (?P<ws>\s+)
        | (?P<comment>[;$].*)
        | (?P<string>"[^"]*")
        | (?P<expr>\{[^}]*\})
        | (?P<number>[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?
              (?:meg|mil|[tgkmunpfa])?)
        | (?P<op>[=(),<>])
        | (?P<word>[A-Za-z_][A-Za-z0-9_.:]*)
        | (?P<other>.)
        """,
        re.IGNORECASE | re.VERBOSE,
    )

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setDefaultColor(self.color(self.DEFAULT))
        self._last_lines = -1            # for fold recompute throttling

    # ── QsciLexerCustom interface ────────────────────────────────────
    def language(self):
        return "SPICE"

    def description(self, style):
        return self._NAMES.get(style, "")

    def styleText(self, start, end):
        editor = self.editor()
        if editor is None:
            return
        # Restyle only the dirty line range Scintilla asked for, not the
        # whole document — keystroke cost stays flat as files grow.
        first = editor.SendScintilla(_SCI_LINEFROMPOSITION, start)
        last = editor.SendScintilla(_SCI_LINEFROMPOSITION, end)
        self.startStyling(
            editor.SendScintilla(_SCI_POSITIONFROMLINE, first))
        in_control = self._in_control_at(editor, first)
        title_deck = self._is_title_deck(editor)
        for line_no in range(first, last + 1):
            raw = editor.text(line_no)
            body = raw.rstrip("\r\n")
            if line_no == 0 and title_deck:
                # Whole first line is the deck title; style it as a
                # comment regardless of what it starts with.
                if body:
                    self.setStyling(_blen(body), self.COMMENT)
            else:
                for chunk, style in self._segments(body, in_control):
                    self.setStyling(_blen(chunk), style)
            eol = len(raw) - len(body)
            if eol:
                self.setStyling(eol, self.DEFAULT)
            tok = self._directive_token(body)
            if tok == ".control":
                in_control = True
            elif tok == ".endc":
                in_control = False

        # Fold structure depends on the whole file; recompute only when
        # the line count changes (covers adding/removing a directive).
        if editor.lines() != self._last_lines:
            self._last_lines = editor.lines()
            self._fold(editor)

    @staticmethod
    def _is_title_deck(editor):
        path = getattr(editor, "file_path", "")
        return os.path.splitext(path)[1].lower() in _TITLE_DECK_EXT

    def _in_control_at(self, editor, line):
        """True if *line* sits inside an open ``.control`` block."""
        in_control = False
        for n in range(line):
            tok = self._directive_token(editor.text(n))
            if tok == ".control":
                in_control = True
            elif tok == ".endc":
                in_control = False
        return in_control

    # ── folding (.subckt/.control/.if … blocks) ──────────────────────
    def _fold(self, editor):
        total = editor.lines()
        if total > _FOLD_LINE_LIMIT:
            return
        depth = 0
        for line_no in range(total):
            tok = self._directive_token(editor.text(line_no))
            level = _SC_FOLDLEVELBASE + depth
            if tok in _FOLD_OPEN:
                editor.SendScintilla(
                    _SCI_SETFOLDLEVEL, line_no,
                    level | _SC_FOLDLEVELHEADERFLAG)
                depth += 1
            elif tok in _FOLD_CLOSE:
                depth = max(0, depth - 1)
                editor.SendScintilla(
                    _SCI_SETFOLDLEVEL, line_no, _SC_FOLDLEVELBASE + depth)
            else:
                editor.SendScintilla(_SCI_SETFOLDLEVEL, line_no, level)

    @staticmethod
    def _directive_token(raw):
        stripped = raw.lstrip()
        if not stripped.startswith("."):
            return ""
        match = re.match(r"\.[A-Za-z]+", stripped)
        return match.group(0).lower() if match else ""

    # ── tokenising ───────────────────────────────────────────────────
    def _segments(self, line, in_control=False):
        n = len(line)
        segs = []
        indent = 0
        while indent < n and line[indent] in " \t":
            indent += 1
        if indent:
            segs.append((line[:indent], self.DEFAULT))
        rest = line[indent:]
        if not rest:
            return segs

        if rest[0] == "*":                       # full-line comment
            segs.append((rest, self.COMMENT))
            return segs

        pos = indent
        element = False                          # is this an element line?
        if rest[0] == "+":                       # line continuation
            segs.append(("+", self.OPERATOR))
            pos = indent + 1
        elif rest[0] == ".":                     # .directive
            match = re.match(r"\.[A-Za-z_]+", rest)
            token = match.group(0) if match else rest
            segs.append((token, self.DIRECTIVE))
            pos = indent + len(token)
        elif in_control:                         # ngspice command word
            match = re.match(r"[A-Za-z_]\w*", rest)
            if match:
                segs.append((match.group(0), self.COMMAND))
                pos = indent + len(match.group(0))
        elif rest[0].upper() in _DEVICE_LETTERS and rest[0].isalpha():
            token = re.match(r"\S+", rest).group(0)
            segs.append((token, self.INSTANCE))
            pos = indent + len(token)
            element = True                       # nodes/values follow

        segs.extend(self._scan(line, pos, element))
        return segs

    def _scan(self, line, pos, element=False):
        segs = []
        n = len(line)
        while pos < n:
            match = self._TOKEN_RE.match(line, pos)
            token = match.group(0)
            kind = match.lastgroup
            if kind == "comment":
                style = self.COMMENT
            elif kind == "string":
                style = self.STRING
            elif kind == "expr":
                style = self.EXPRESSION
            elif kind == "number":
                style = self.NUMBER
            elif kind == "op":
                style = self.OPERATOR
            elif kind == "word":
                end = match.end()
                if end < n and line[end] == "(":      # foo( → function
                    style = self.FUNCTION
                elif self._is_param(line, end):       # name= → parameter
                    style = self.PARAMETER
                elif element and token.lower() in _SOURCE_KEYWORDS:
                    style = self.FUNCTION             # DC/AC/SIN/PULSE…
                elif element:
                    style = self.NODE                 # net / connectivity
                else:
                    style = self.DEFAULT
            else:
                style = self.DEFAULT
            segs.append((token, style))
            pos = match.end()
        return segs

    @staticmethod
    def _is_param(line, after):
        n = len(line)
        while after < n and line[after] in " \t":
            after += 1
        return after < n and line[after] == "="


# SystemVerilog keywords the stock QScintilla Verilog lexer (whose primary
# keyword set is Verilog-2001 era) doesn't know, so ``logic``, ``always_ff``,
# the SV integer types, ``typedef``/``enum``/``struct`` etc. would otherwise
# render as plain identifiers.  Scoped to synthesizable RTL constructs (this
# tool's domain); verification/OOP keywords (class, assert, constraint, …) are
# deliberately omitted so they can't recolour identifiers in legacy code.
_SYSTEMVERILOG_KEYWORDS = (
    "logic bit byte int shortint longint shortreal void chandle string "
    "enum struct union packed typedef var const ref "
    "always_ff always_comb always_latch final "
    "unique unique0 priority iff inside "
    "foreach return break continue do "
    "interface endinterface modport package endpackage program endprogram "
    "import export extern timeunit timeprecision"
)


class VerilogLexer(QsciLexerVerilog):
    """Verilog/SystemVerilog lexer with a refreshed keyword set.

    The stock primary keyword set predates SystemVerilog and also ships a
    data defect (``endprimitiveendspecify`` with no separating space, so
    neither word is recognised).  This repairs that join and folds in the
    common SystemVerilog keywords on top of whatever QScintilla ships.
    """

    def keywords(self, kset):
        if kset == 1:                       # primary keyword set (style 5)
            base = super().keywords(kset) or ""
            base = base.replace(
                "endprimitiveendspecify", "endprimitive endspecify")
            return base + " " + _SYSTEMVERILOG_KEYWORDS
        return super().keywords(kset)


def language_for(file_path):
    """Return a short language label for *file_path*."""
    ext = _ext(file_path)
    if ext in _SPICE_EXT:
        return "SPICE"
    if ext in _VERILOG_EXT:
        return "Verilog"
    if ext in _VHDL_EXT:
        return "VHDL"
    return "Text"


def is_generated(file_path):
    """True if *file_path* is an eSim-generated (output) file."""
    return _ext(file_path) in GENERATED_EXT


def comment_token(file_path):
    """Return the line-comment prefix for *file_path*'s language."""
    lang = language_for(file_path)
    if lang == "SPICE":
        return "*"
    if lang == "VHDL":
        return "--"
    if lang == "Verilog":
        return "//"
    return None


def make_lexer(file_path, font, parent=None):
    """Build a lexer for *file_path*, or ``None`` for plain text.

    *parent* must own the lexer so it is not garbage-collected.
    """
    if not HAS_QSCI:
        # No QScintilla: the host is showing a PlainEditor, which has no
        # lexer slot to fill.
        return None
    lang = language_for(file_path)
    lexer = None
    if lang == "SPICE":
        lexer = SpiceLexer(parent)
    elif lang == "Verilog":
        lexer = VerilogLexer(parent)
    elif lang == "VHDL":
        lexer = QsciLexerVHDL(parent)

    if lexer is not None:
        lexer.setDefaultFont(font)
        lexer.setFont(font)
    return lexer


def _ext(file_path):
    return os.path.splitext(file_path)[1].lower()
