"""Lexers and language detection for the eSim code editor.

SPICE gets a purpose-built :class:`SpiceLexer` (the stock Scintilla
SPICE lexer cannot distinguish a component instance from a node and
miscolours stray single letters).  Verilog and VHDL use Scintilla's
mature built-in lexers.
"""

import os
import re

from PyQt6.Qsci import (
    QsciLexerCustom,
    QsciLexerVerilog,
    QsciLexerVHDL,
    QsciScintilla,
)


# Scintilla fold-level flags (stable ABI constants).
_SC_FOLDLEVELBASE = 0x400
_SC_FOLDLEVELHEADERFLAG = 0x2000
_SCI_SETFOLDLEVEL = getattr(QsciScintilla, "SCI_SETFOLDLEVEL", 2222)
_SCI_LINEFROMPOSITION = getattr(QsciScintilla, "SCI_LINEFROMPOSITION", 2166)
_SCI_POSITIONFROMLINE = getattr(QsciScintilla, "SCI_POSITIONFROMLINE", 2167)

# Above this many lines we skip the (full-document) fold recompute to
# keep very large netlists responsive.
_FOLD_LINE_LIMIT = 20000

# Directives that open / close a foldable region.
_FOLD_OPEN = {".subckt", ".control", ".if", ".macro"}
_FOLD_CLOSE = {".ends", ".endc", ".endif", ".eom"}


def _blen(chunk):
    """Byte length of *chunk* (Scintilla styles in bytes)."""
    return len(chunk) if chunk.isascii() else len(chunk.encode("utf-8"))


# Extensions grouped by language (lower-case, with leading dot).
_SPICE_EXT = {
    ".cir", ".cirout", ".sub", ".lib", ".mod", ".net", ".ckt",
    ".sp", ".spice", ".cki", ".inc",
}
_VERILOG_EXT = {".v", ".va", ".vams", ".sv", ".vh"}
_VHDL_EXT = {".vhd", ".vhdl"}

# Files generated by eSim / ngspice and overwritten on the next run.
GENERATED_EXT = {".cirout", ".out", ".log"}

# SPICE element letters: first char of an instance line.
_DEVICE_LETTERS = set("RCLVIDQMXBEFGHJKSTWOUZPA")


class SpiceLexer(QsciLexerCustom):
    """Grammar-aware SPICE / ngspice netlist lexer."""

    DEFAULT = 0
    COMMENT = 1
    DIRECTIVE = 2
    INSTANCE = 3
    NUMBER = 4
    PARAMETER = 5
    STRING = 6
    OPERATOR = 7
    EXPRESSION = 8
    COMMAND = 9
    FUNCTION = 10

    _NAMES = {
        0: "Default", 1: "Comment", 2: "Directive",
        3: "Instance device", 4: "Number", 5: "Parameter",
        6: "String", 7: "Operator", 8: "Expression",
        9: "Command", 10: "Function",
    }

    # in-line token scanner (applied after the positional first token)
    _TOKEN_RE = re.compile(
        r"""
          (?P<ws>\s+)
        | (?P<comment>[;$].*)
        | (?P<string>"[^"]*")
        | (?P<expr>\{[^}]*\})
        | (?P<number>[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?
              (?:meg|mil|[tgkmunpf])?)
        | (?P<op>[=(),<>])
        | (?P<word>[A-Za-z_][A-Za-z0-9_.:]*)
        | (?P<other>.)
        """,
        re.IGNORECASE | re.VERBOSE,
    )

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setDefaultColor(self.color(self.DEFAULT))
        self._last_lines = -1            # for fold recompute throttling

    # ── QsciLexerCustom interface ────────────────────────────────────
    def language(self):
        return "SPICE"

    def description(self, style):
        return self._NAMES.get(style, "")

    def styleText(self, start, end):
        editor = self.editor()
        if editor is None:
            return
        # Restyle only the dirty line range Scintilla asked for, not the
        # whole document — keystroke cost stays flat as files grow.
        first = editor.SendScintilla(_SCI_LINEFROMPOSITION, start)
        last = editor.SendScintilla(_SCI_LINEFROMPOSITION, end)
        self.startStyling(
            editor.SendScintilla(_SCI_POSITIONFROMLINE, first))
        in_control = self._in_control_at(editor, first)
        for line_no in range(first, last + 1):
            raw = editor.text(line_no)
            body = raw.rstrip("\r\n")
            for chunk, style in self._segments(body, in_control):
                self.setStyling(_blen(chunk), style)
            eol = len(raw) - len(body)
            if eol:
                self.setStyling(eol, self.DEFAULT)
            tok = self._directive_token(body)
            if tok == ".control":
                in_control = True
            elif tok == ".endc":
                in_control = False

    def _in_control_at(self, editor, line):
        """True if *line* sits inside an open ``.control`` block."""
        in_control = False
        for n in range(line):
            tok = self._directive_token(editor.text(n))
            if tok == ".control":
                in_control = True
            elif tok == ".endc":
                in_control = False
        return in_control

        # Fold structure depends on the whole file; recompute only when
        # the line count changes (covers adding/removing a directive).
        if editor.lines() != self._last_lines:
            self._last_lines = editor.lines()
            self._fold(editor)

    # ── folding (.subckt/.control/.if … blocks) ──────────────────────
    def _fold(self, editor):
        total = editor.lines()
        if total > _FOLD_LINE_LIMIT:
            return
        depth = 0
        for line_no in range(total):
            tok = self._directive_token(editor.text(line_no))
            level = _SC_FOLDLEVELBASE + depth
            if tok in _FOLD_OPEN:
                editor.SendScintilla(
                    _SCI_SETFOLDLEVEL, line_no,
                    level | _SC_FOLDLEVELHEADERFLAG)
                depth += 1
            elif tok in _FOLD_CLOSE:
                depth = max(0, depth - 1)
                editor.SendScintilla(
                    _SCI_SETFOLDLEVEL, line_no, _SC_FOLDLEVELBASE + depth)
            else:
                editor.SendScintilla(_SCI_SETFOLDLEVEL, line_no, level)

    @staticmethod
    def _directive_token(raw):
        stripped = raw.lstrip()
        if not stripped.startswith("."):
            return ""
        match = re.match(r"\.[A-Za-z]+", stripped)
        return match.group(0).lower() if match else ""

    # ── tokenising ───────────────────────────────────────────────────
    def _segments(self, line, in_control=False):
        n = len(line)
        segs = []
        indent = 0
        while indent < n and line[indent] in " \t":
            indent += 1
        if indent:
            segs.append((line[:indent], self.DEFAULT))
        rest = line[indent:]
        if not rest:
            return segs

        if rest[0] == "*":                       # full-line comment
            segs.append((rest, self.COMMENT))
            return segs

        pos = indent
        if rest[0] == "+":                       # line continuation
            segs.append(("+", self.OPERATOR))
            pos = indent + 1
        elif rest[0] == ".":                     # .directive
            match = re.match(r"\.[A-Za-z_]+", rest)
            token = match.group(0) if match else rest
            segs.append((token, self.DIRECTIVE))
            pos = indent + len(token)
        elif in_control:                         # ngspice command word
            match = re.match(r"[A-Za-z_]\w*", rest)
            if match:
                segs.append((match.group(0), self.COMMAND))
                pos = indent + len(match.group(0))
        elif rest[0].upper() in _DEVICE_LETTERS and rest[0].isalpha():
            token = re.match(r"\S+", rest).group(0)
            segs.append((token, self.INSTANCE))
            pos = indent + len(token)

        segs.extend(self._scan(line, pos))
        return segs

    def _scan(self, line, pos):
        segs = []
        n = len(line)
        while pos < n:
            match = self._TOKEN_RE.match(line, pos)
            token = match.group(0)
            kind = match.lastgroup
            if kind == "comment":
                style = self.COMMENT
            elif kind == "string":
                style = self.STRING
            elif kind == "expr":
                style = self.EXPRESSION
            elif kind == "number":
                style = self.NUMBER
            elif kind == "op":
                style = self.OPERATOR
            elif kind == "word":
                end = match.end()
                if end < n and line[end] == "(":      # foo( → function
                    style = self.FUNCTION
                elif self._is_param(line, end):
                    style = self.PARAMETER
                else:
                    style = self.DEFAULT
            else:
                style = self.DEFAULT
            segs.append((token, style))
            pos = match.end()
        return segs

    @staticmethod
    def _is_param(line, after):
        n = len(line)
        while after < n and line[after] in " \t":
            after += 1
        return after < n and line[after] == "="


def language_for(file_path):
    """Return a short language label for *file_path*."""
    ext = _ext(file_path)
    if ext in _SPICE_EXT:
        return "SPICE"
    if ext in _VERILOG_EXT:
        return "Verilog"
    if ext in _VHDL_EXT:
        return "VHDL"
    return "Text"


def is_generated(file_path):
    """True if *file_path* is an eSim-generated (output) file."""
    return _ext(file_path) in GENERATED_EXT


def comment_token(file_path):
    """Return the line-comment prefix for *file_path*'s language."""
    lang = language_for(file_path)
    if lang == "SPICE":
        return "*"
    if lang == "VHDL":
        return "--"
    if lang == "Verilog":
        return "//"
    return None


def make_lexer(file_path, font, parent=None):
    """Build a lexer for *file_path*, or ``None`` for plain text.

    *parent* must own the lexer so it is not garbage-collected.
    """
    lang = language_for(file_path)
    lexer = None
    if lang == "SPICE":
        lexer = SpiceLexer(parent)
    elif lang == "Verilog":
        lexer = QsciLexerVerilog(parent)
    elif lang == "VHDL":
        lexer = QsciLexerVHDL(parent)

    if lexer is not None:
        lexer.setDefaultFont(font)
        lexer.setFont(font)
    return lexer


def _ext(file_path):
    return os.path.splitext(file_path)[1].lower()
